In [1]:
import pandas as pd
from collections import Counter

In [13]:
country_full = {
    'AT':'Austria', 'BE':'Belgium', 'BG':'Bulgaria', 'HR':'Croatia', 'CY': 'Cyprus', 
    'CZ':'Czech Republic', 'DK':'Denmark', 'EE':'Estonia','FI':'Finland', 'FR':'France',
    'DE':'Germany', 'GR':'Greece', 'HU':'Hungary', 'IE':'Ireland','IT':'Italy', 
    'LV':'Latvia', 'LT':'Lithuania','LU':'Luxembourg', 'MT':'Malta', 'NL':'Netherlands', 
    'PL':'Poland', 'PT':'Portugal', 'RO':'Romania', 'SK':'Slovakia', 'SI':'Slovenia',
    'ES':'Spain', 'SE':'Sweden'}

### country job vacancies

In [165]:
file = 'data/job_vacancies.tsv'
df = pd.read_table(file)

In [166]:
df.columns = [col.strip() for col in df.columns]

In [167]:
df[['s_adj','nace_r2','sizeclas','index', 'country']] = df[df.columns[0]].str.split(',', expand=True)
df = df.drop(df.columns[0], axis=1)

In [163]:
# replacing with full names of the countries
df['country'] = df['country'].replace(country_full)

In [168]:
df['country'].values

array(['AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'EA19', 'EA20', 'EE',
       'EL', 'ES', 'EU27_2020', 'FI', 'HR', 'HU', 'IE', 'IS', 'IT', 'LT',
       'LU', 'LV', 'MK', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE', 'SI',
       'SK', 'AT', 'BE', 'BG', 'CH', 'CY', 'CZ', 'DE', 'EA19', 'EA20',
       'EE', 'EL', 'ES', 'EU27_2020', 'FI', 'HR', 'HU', 'IE', 'IS', 'IT',
       'LT', 'LU', 'LV', 'MK', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SE',
       'SI', 'SK'], dtype=object)

In [144]:
# leaving only the required countries
df = df[df['country'].isin(list(country_full.values()))]

In [145]:
# leaving only the year 2022 and the required columns
df = df[['2022Q1', '2022Q2','2022Q3','2022Q4','2023Q1', '2023Q2', 'index','country']]

In [146]:
# removing Job Vacancy because it has null values
df = df[(df['index']=='JOBRATE')]

In [147]:
columns_to_process = ['2022Q1', '2022Q2','2022Q3','2022Q4','2023Q1', '2023Q2']
for column in columns_to_process:
    df[column] = df[column].str.replace(' p', '').astype(float)

In [148]:
df = df.drop(columns=['index'])

In [149]:
df = df.sort_values(by='country')

In [150]:
df

    2022Q1  2022Q2  2022Q3  2022Q4  2023Q1  2023Q2         country
0      4.7     4.8     5.0     4.6     4.7     4.4         Austria
1      4.8     5.0     4.9     4.5     4.7     4.6         Belgium
2      0.9     0.9     0.8     0.8     0.9     0.8        Bulgaria
14     2.1     1.7     1.2     1.4     2.1     1.7         Croatia
4      3.2     2.7     2.2     1.9     2.8     2.9          Cyprus
5      5.3     4.9     4.5     4.2     3.8     3.7  Czech Republic
9      2.1     2.1     2.1     1.8     1.9     1.8         Estonia
13     3.9     3.0     2.5     2.0     3.3     2.2         Finland
6      4.1     4.5     4.3     4.4     4.1     4.1         Germany
15     2.7     3.0     2.8     2.5     2.6     2.5         Hungary
16     1.6     1.6     1.6     1.3     1.4     1.3         Ireland
18     2.5     2.3     2.1     1.9     2.6     2.4           Italy
21     3.2     2.9     2.9     2.5     2.7     2.8          Latvia
19     2.0     2.0     1.9     1.7     1.9     2.0       Lithuania
20     2.3     2.7     2.7     2.4     2.2     1.9      Luxembourg
23     2.5     2.8     2.8     2.5     2.6     2.7           Malta
24     4.9     5.1     4.9     4.5     4.7     4.7     Netherlands
26     1.3     1.2     1.1     0.9     0.9     0.9          Poland
27     1.3     1.4     1.7     1.5     1.3     1.5        Portugal
28     1.0     0.9     0.9     0.8     0.9     0.8         Romania
31     1.1     1.0     1.1     1.0     1.1     1.0        Slovakia
30     3.2     3.3     3.1     2.5     3.0     2.9        Slovenia
11     0.9     0.9     0.9     0.9     0.9     0.9           Spain
29     3.6     3.6     2.7     2.6     3.7     3.2          Sweden

In [151]:
df.to_csv('data/job_vacancies.csv', index=False)

### country healthcare

In [25]:
file = 'data/country_healthcare.csv'
df = pd.read_csv(file)

In [26]:
df = df[df['name'].isin(list(country_full.values()))]

In [27]:
df

,skill_and_competency,cost,responsiveness_waitings,index_healthcare,speed,accuracy_and_completeness,friendliness_and_courtesy,modern_equipment,name,monthLastUpdate,location,contributors,yearLastUpdate,percentage_insurance_employer,percentage_insurance_private,percentage_insurance_public,percentage_insurance_none
0,1.113565,1.127796,0.444444,76.423305,1.016026,1.113333,0.838608,1.436893,Austria,9,1.293930,318,2023,13.207547,8.176101,77.044025,1.572327
1,1.155894,0.911538,0.532567,75.303587,0.908397,1.062016,0.938697,1.474903,Belgium,10,1.213740,263,2023,24.334601,20.532319,53.231939,1.901141
2,0.410390,0.461140,-0.288714,57.150219,0.412533,0.149051,-0.098958,0.112000,Bulgaria,10,0.955497,389,2023,25.449871,9.768638,57.840617,6.940874
3,0.813896,1.022388,-0.456790,64.812469,0.064516,0.607500,0.572840,0.621554,Croatia,10,1.064198,408,2023,15.686275,7.352941,75.735294,1.225490
4,0.149606,0.280000,-0.162602,56.007964,0.137097,0.108333,0.377953,0.358333,Cyprus,10,0.634146,128,2023,21.875000,27.343750,37.500000,13.281250
5,1.193900,1.419426,0.194323,75.371738,0.842451,0.948956,0.479212,1.298441,Czech Republic,10,1.337691,463,2023,13.174946,7.775378,77.537797,1.511879
6,1.074561,1.554545,0.292237,78.303079,0.650000,1.013953,1.283186,1.533937,Denmark,10,1.232143,230,2023,7.826087,5.652174,78.260870,8.260870
7,1.081731,1.310345,0.111650,75.843660,0.786408,1.155000,0.729469,1.485437,Estonia,9,1.333333,209,2023,7.177033,3.827751,80.382775,8.612440
8,1.192053,1.170068,0.429530,77.380389,0.886667,1.176471,0.996644,1.562712,Finland,10,1.272727,304,2023,19.078947,11.513158,56.578947,12.828947
9,1.306250,1.345912,0.454737,78.521358,1.018789,1.160944,0.880503,1.436170,France,10,1.318471,484,2023,29.752066,14.669421,53.099174,2.479339
10,1.000958,0.875849,0.083739,71.726383,0.743891,0.936799,0.658892,1.419715,Germany,10,1.225806,1048,2023,10.782443,14.312977,74.236641,0.667939
11,0.559420,0.472914,-0.590379,57.193414,-0.026277,0.310292,0.382824,0.307922,Greece,9,0.700000,696,2023,11.781609,10.632184,72.988506,4.597701
12,0.511545,0.565217,-0.783542,54.107799,-0.362989,0.243590,-0.078292,0.147810,Hungary,10,0.670251,565,2023,8.141593,5.132743,83.008850,3.716814
13,0.166667,-0.278826,-0.874477,51.695935,-0.343035,0.179654,0.912500,0.643478,Ireland,10,0.483402,489,2023,18.200409,33.333333,30.061350,18.404908
14,0.922436,0.735484,-0.322907,65.775995,0.177331,0.838167,0.587097,1.096082,Italy,10,0.910185,1105,2023,7.330317,3.619910,76.380090,12.669683
15,0.722973,0.290541,-0.217687,62.997356,0.517007,0.561644,0.523810,0.854167,Latvia,9,1.136054,148,2023,25.000000,9.459459,45.945946,19.594595
16,0.942857,1.195402,0.262857,73.406136,0.789773,0.839286,0.620690,1.267442,Lithuania,10,1.312500,176,2023,13.068182,4.545455,79.545455,2.840909
17,1.062500,0.809524,0.687500,76.441992,1.312500,1.064516,0.921875,1.491803,Luxembourg,10,1.359375,65,2023,12.307692,26.153846,61.538462,NaN
18,0.128205,0.220779,-0.448718,52.098121,-0.153846,0.051282,0.105263,0.328947,Malta,10,0.302632,78,2023,19.230769,14.102564,55.128205,11.538462
19,1.202997,0.855372,0.859504,79.361228,1.107143,1.222222,1.282759,1.688112,Netherlands,10,1.496561,736,2023,7.065217,36.956522,55.163043,0.815217
20,0.341040,0.485207,-0.556204,58.391319,0.114826,0.378582,0.196193,0.750000,Poland,10,0.826023,696,2023,31.034483,13.505747,53.017241,2.442529
21,1.109434,1.041509,0.057143,72.619607,0.574427,0.947266,1.066038,1.073218,Portugal,10,1.232514,535,2023,16.448598,18.504673,52.523364,12.523364
22,0.445087,0.270396,-0.373690,56.366870,0.132641,0.335322,0.092166,0.283863,Romania,10,0.835891,871,2023,25.028703,7.807118,61.308840,5.855339
23,0.481928,0.773006,-0.693252,59.418035,0.098765,0.519481,0.127273,0.377358,Slovakia,10,0.932927,166,2023,12.048193,11.445783,74.698795,1.807229
24,0.897297,1.116022,-0.693989,66.946833,0.151351,0.670391,0.736264,0.890110,Slovenia,10,1.217391,185,2023,21.621622,11.891892,65.405405,1.081081
25,1.246809,1.413681,0.165236,77.584774,0.674597,1.100656,1.075612,1.447084,Spain,10,1.393162,946,2023,7.399577,18.710359,67.547569,6.342495
26,0.653509,1.053571,-0.251656,68.700318,0.195067,0.706019,0.913140,1.424379,Sweden,10,0.984513,459,2023,9.368192,5.664488,76.906318,8.061002

In [28]:
df = df[['name','percentage_insurance_employer', 'percentage_insurance_private', 'percentage_insurance_public', 'percentage_insurance_none']]

In [30]:
df.columns

Index(['name', 'percentage_insurance_employer', 'percentage_insurance_private',
       'percentage_insurance_public', 'percentage_insurance_none'],
      dtype='object')

In [32]:
df = df.rename(columns={'percentage_insurance_employer':"by_employer", 'percentage_insurance_private':"private",
       'percentage_insurance_public':"by_public", 'percentage_insurance_none':"others"})

In [7]:
# Reshape the DataFrame using melt
df_melted = pd.melt(df, id_vars=['name'], var_name='insurance_source', value_name='proportion')

# Map the insurance sources to desired names
source_mapping = {
    'percentage_insurance_employer': 'employer',
    'percentage_insurance_private': 'private',
    'percentage_insurance_public': 'public',
    'percentage_insurance_none': 'others'
}

df_melted['insurance_source'] = df_melted['insurance_source'].map(source_mapping)

# Format the proportion column
df_melted['proportion'] = df_melted['proportion'].apply(lambda x: f'{x:.3f}')

# Print the result
print(df_melted)

         name insurance_source proportion
0     Austria         employer     13.208
1     Belgium         employer     24.335
2    Bulgaria         employer     25.450
3     Croatia         employer     15.686
4      Cyprus         employer     21.875
..        ...              ...        ...
103   Romania           others      5.855
104  Slovakia           others      1.807
105  Slovenia           others      1.081
106     Spain           others      6.342
107    Sweden           others      8.061

[108 rows x 3 columns]

In [8]:
df_melted

         name insurance_source proportion
0     Austria         employer     13.208
1     Belgium         employer     24.335
2    Bulgaria         employer     25.450
3     Croatia         employer     15.686
4      Cyprus         employer     21.875
..        ...              ...        ...
103   Romania           others      5.855
104  Slovakia           others      1.807
105  Slovenia           others      1.081
106     Spain           others      6.342
107    Sweden           others      8.061

[108 rows x 3 columns]

In [23]:
df = df.iloc[:2]

In [33]:
df.to_csv('data/insurance_proportion.csv', index=False)